### ISSUE TITLE
Host on a domain at friendlycode.org

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/grparks#32]
I'm thinking: friendlycode.org/grparks

**Comment by joel6653** [comment]
We have the go-ahead from the City to host it on some sort of "shared server" that FriendlyCode supposedly has access to.  Does anyone have expertise/knowledge in this area? Specifically, how to move this into production from GitHub onto that other server.

As a related issue, I'm looking for a way to transition all the automation (automatic rebuilding) that we have in place on GitHub. Also, it would be nice if we could automate the js minification and the css minification process.

**Comment by jacebrowning** [comment]
I'm comfortable doing this. I just need more information about the infrastructure we'd be hosting on and some credentials to access it. Ideally, we can continue to deploy to GitHub pages and add in the city's infrastructure as a second deployment location.

**Comment by Crevax** [comment]
I've got some Gulp scripts I can re-purpose for concatenation/minification of the js and css, and also handle FTP'ing for deployment to the city's server. I'll take a look at setting that up during my lunch break today.

**Comment by Crevax** [comment]
I've got the gulp tasks for css and js in the feature/gulp-tasks branch. I didn't have time to add it into the Make pipeline or test through it. I'll wrap the up tonight.

**Comment by joel6653** [comment]
I think this is resolved. May we close the issue?

**Comment by joel6653** [comment]
Superseded. Now hosted at grparks.citizenlabs.org.

**Comment by jacebrowning** [comment]
@joel6653 You should be able to close issues now. Please try closing this.
