### ISSUE TITLE
Add CNAME for grparks.citizenlabs.org

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/grparks#49]
Currently, grparks.citizenlabs.org is redirecting to http://citizenlabsgr.github.io/grparks/, but ultimately I think we'd like this to be an alias.

**Comment by Allen616** [comment]
I have changed the forwarding settings from 1and1.com. I know the terminology is different, let me know if this is what you had in mind.  [grparks.citizenlabs.org](http://grparks.citizenlabs.org)

**Comment by jacebrowning** [comment]
Yeah, looks good!
