### ISSUE TITLE
Add a timestamp to the build output

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/grparks#52]
This will let us display "data last updated xxxx" on the site.

**Comment by jacebrowning** [comment]
@joel6653 What format will be easiest to read from Javascript?

**Comment by joel6653** [comment]
Pretty much any valid date format. If it were already in a format suitable for displaying to the public, I wouldn't even have to convert it.  (Something like "August 12, 2016" would be ideal.) I'm glad that you jumped on this so quickly, but let's hold off for a day or so. I've given Karie the option of including a different last-updated date for each park (which is something she would simply enter in the spreadsheet, row-by-row); if she likes that idea, then we'll forgo doing it your way.

**Comment by jacebrowning** [comment]
A date in the CSV would be even better!

**Comment by joel6653** [comment]
got OK from Karie, this is the way she'd prefer to go (to be clear, I mean your suggested method, rather than the one I made about including a different last-updated date for each park)

**Comment by joel6653** [comment]
to be clear again, this date should change ONLY when she is publishing a new .csv file, but not when I (we) are making code changes that cause the site to get rebuilt

**Comment by jacebrowning** [comment]
I'm going to try to read the modification date from the CSV and write it to a JSON file.

**Comment by joel6653** [comment]
As it turns out, the "data" folder isn't in the path available to my scripts (which are in the "pages" folder).  Is it possible to put the txt file in with the html in the "pages" folder?
