### ISSUE TITLE
Add an icon for mobile application shortcuts

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/grparks#53]
@joel6653 Is there a way to add this metadata to the index?

**Comment by joel6653** [comment]
It works on iOS devices. Do you know what the name of the meta tag is for Android?

**Comment by jacebrowning** [comment]
No, but it's one of these: https://github.com/votestakes/votestakes-site/blob/f186ccf6804dd7ab366e5a7ab890b7a1a7e59282/public/index.html#L14-L33

**Comment by jacebrowning** [comment]
That code was generated by http://realfavicongenerator.net/.

**Comment by joel6653** [comment]
I just remembered why I didn't follow all the way through on this before: I don't have a custom icon. I was happy with the one that is generated (by mobile Safari, at least) by default. It's a miniaturized screenshot. I'm not creative enough, graphically speaking, to make one of my own. Got any ideas?

**Comment by jacebrowning** [comment]
Some ideas:

- The City of Grand Rapids logo
- A simplified outline of the Grand Rapids boundary
- The Calder shape filled with nature (trees, grass, etc.) 

Maybe @BrandonKlotz could help make one?

**Comment by BrandonKlotz** [comment]
Is this Icon for a Favicon? Or a heading icon?

**Comment by joel6653** [comment]
Sort of like a Favicon, but not really the same thing. It should be specified in a rather large variety of sizes, in order to accommodate the different screen sizes and resolutions of mobile devices. When you browse to the page, you can add the page to your homescreen for quicker access. This icon will be used to represent the page/"app" on your screen. Specified through a series of meta tags.

**Comment by jacebrowning** [comment]
It could also be used as the favicon. http://realfavicongenerator.net will generate all the sizes we need.

**Comment by BrandonKlotz** [comment]
These are a couple variations of an icon that combines Calder imagery & parks.  Let me know your thoughts!
![gr_parks-06](https://cloud.githubusercontent.com/assets/19940878/17265978/71667824-55c1-11e6-9994-86c201842de0.png)
![gr_parks-07](https://cloud.githubusercontent.com/assets/19940878/17265980/71729294-55c1-11e6-850a-4d54ec984761.png)
![gr_parks-08](https://cloud.githubusercontent.com/assets/19940878/17265979/71711b12-55c1-11e6-969a-76cd60d41882.png)

**Comment by jacebrowning** [comment]
I like 3 the best!

**Comment by joel6653** [comment]
Any one of them would be fine. What kind of background color would you propose that I put them on? (Keep in mind that the OS wants a square-ish icon.)

**Comment by BrandonKlotz** [comment]
I would say white would look good otherwise, let me send you it all in SVG form when I get back to my computer.

**Comment by BrandonKlotz** [comment]
Below are SVG of the 3rd Icon with background colors, and a new icon idea.

![gr_parks-09](https://cloud.githubusercontent.com/assets/19940878/17272063/ba1de4f0-565a-11e6-8e11-497722c0ae0a.png)

[SVGIcons.zip](https://github.com/citizenlabsgr/grparks/files/392014/SVGIcons.zip)

**Comment by joel6653** [comment]
Love the latest one, the map marker, but the background is too large, making the marker itself very small when Jace's site processes it.

**Comment by BrandonKlotz** [comment]
Here is a SVG and PNG with no border so you can add padding/margins with code.

[Borderless.zip](https://github.com/citizenlabsgr/grparks/files/392645/Borderless.zip)

**Comment by MuellerL** [comment]
I love what you fellas are doing.


--
All the best,
Lee

**Comment by joel6653** [comment]
@BrandonKlotz, ummm, that's not how Jace's suggested site (see link way above) works. It takes the png (or whatever format graphic), and creates the different sizes and meta tags and such. Borders and margins are css things, but this doesn't use css, purely as-is graphics and resizing are involved.

**Comment by BrandonKlotz** [comment]
Let's try this.
![parks_logo](https://cloud.githubusercontent.com/assets/19940878/17281894/bf6bfa0a-576d-11e6-957f-2cca9adf683c.png)

**Comment by joel6653** [comment]
Done. Used Brandon's latest.

**Comment by jacebrowning** [comment]
Looks good!
